couchdb_config:
     couchdb_host: 172.17.0.2
     couchdb_port: 5984

     token_db: tokendb
     couch_username: admin
     couch_password: admin

     schedule_callerdb: schedcallerdb

     smsdb: smsdb

     schedule_smsdb: schedsmsdb     

     authtokendb: authdb

redis_config:
     redis_host: 172.17.0.3
     redis_port: 6379    

     redis_password: password

     max_connections: 20

     pool_timeout: 3000

     connect_timeout: 3000

     query_timeout: 3000

