couchdb_config:
     couchdb_host: 172.17.0.3
     couchdb_port: 5984

     couch_username: admin
     couch_password: password

     token_db: tokendb
     org_db: organizationdb
     project_db: projectdb
     user_db: userdb

     schedule_callerdb: schedcallerdb

     smsdb: smsdb

     schedule_smsdb: schedsmsdb     

     authtokendb: authdb

redis_config:
     redis_host: 172.17.0.2
     redis_port: 6379    

     redis_password: password

     max_connections: 20

     redis_trial_token_expire: 1296000

     pool_timeout: 3000

     connect_timeout: 3000

     query_timeout: 3000

plivo_config:
     plivo_authid: XXXXXXXXXXXXXXXXXXXXXXXXXXX

     plivo_authtoken: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

     plivo_number: 123456789

     plivo_answerurl: http://healware.com:5000/response/speak
   
     plivo_url: http://hidden-plateau-8325.herokuapp.com/response/conference

